apiVersion: batch/v1
kind: Job
metadata:
  name: echo
spec:
  completions: 2
  parallelism: 2
  template:
    spec:
      containers:
      - name: echo
        image: busybox
        envFrom:
        - configMapRef:
            name: echo-env
        env:
        command: ["sh", "-c"]
        args:
        - |
          echo $WORD
      restartPolicy: Never