apiVersion: batch/v1
kind: Job
metadata:
  name: echo
spec:
  completions: 2
  parallelism: 2
  template:
    spec:
      containers:
      - name: sleep
        image: busybox
        env:
        - name: WORD
          value: "Hello from the environment"
        command: ["sh", "-c"]
        args:
        - |
          echo $WORD
      restartPolicy: Never