apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v1-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-test-v1
  template:
    metadata:
      labels:
        app: hello-test-v1
    spec:
      containers:
      - name: hello-v1
        image: aa332266/hello:v1
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service-v1
spec:
  selector:
    app: hello-test-v1
  ports:
  - protocol: TCP
    port: 8080

