apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-v1-deploy
spec:
  replicas: 8
  selector:
    matchLabels:
      app: hello-test-v1
  template:
    metadata:
      labels:
        app: hello-test-v1
    spec:
      containers:
      - name: hello-v1
        image: aa332266/hello:v1
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 1m # "s", "m", "h".
      - setWeight: 20
      - pause: {} # pause indefinitely
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service-v1
spec:
  selector:
    app: hello-test-v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

